FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD demo-mvn.jar /opt/demo-mvn/
EXPOSE 8080
WORKDIR /opt/demo-mvn/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "demo-mvn.jar"]
